name: Check linting
on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    lint:
        name: Check linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: "yarn"
            - name: Install dependencies
              run: yarn --ignore-scripts
            - name: Lint
              run: yarn lint:ci
